apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test  
  labels:
    app: devops-test 
spec:
  replicas: 4
  selector:
     matchLabels:
       app: devops-test 
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: devops-test 
    spec:
      containers:
        - name: devops-test 
          image: 724526322405.dkr.ecr.us-west-2.amazonaws.com/flutterwaveweb:{{IMAGE_VERSION}}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: devops-test  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: devops-test 
